import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "Canon EOS R6",
    productDescription: "Mirrorless Full-Frame Camera",
    productImage:
      "https://images.unsplash.com/photo-1618894915263-e3ad4d326f07",
    categoryName: "cameras",
    price: 2399,
    discountPercent: 10,
    discountedPrice: 2159,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Sony FE 16-35mm f/2.8 GM Lens",
    productDescription: "Wide-Angle Zoom Lens for Sony E-mount Cameras",
    productImage:
      "https://images.unsplash.com/photo-1620556848045-40d1b9af2e5b",
    categoryName: "lenses",
    price: 2198,
    discountPercent: 0,
    discountedPrice: 2198,
    onSale: false,
    outOfStock: false,
    rating: 4.8,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Manfrotto MT055CXPRO4 Carbon Fiber Tripod",
    productDescription: "Professional Tripod with Carbon Fiber Legs",
    productImage:
      "https://images.unsplash.com/photo-1593093315218-dfb78beec3c1",
    categoryName: "accessories",
    price: 489,
    discountPercent: 0,
    discountedPrice: 489,
    onSale: false,
    outOfStock: false,
    rating: 4.7,
    trending: false,
  },
  {
    _id: uuid(),
    productName: "Nikon D850",
    productDescription: "Full-Frame DSLR Camera",
    productImage:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    categoryName: "cameras",
    price: 2999,
    discountPercent: 15,
    discountedPrice: 2549,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Canon EF 70-200mm f/2.8L IS III USM Lens",
    productDescription: "Telephoto Zoom Lens for Canon DSLR Cameras",
    productImage: "https://images.unsplash.com/photo-1563254019-09f0f0aa61b5",
    categoryName: "lenses",
    price: 2099,
    discountPercent: 0,
    discountedPrice: 2099,
    onSale: false,
    outOfStock: false,
    rating: 4.8,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Profoto A1X AirTTL-N Studio Light for Nikon",
    productDescription: "Portable Studio Flash for Nikon Cameras",
    productImage:
      "https://images.unsplash.com/photo-1576878104087-28fb4c4d5cc2",
    categoryName: "lighting",
    price: 1099,
    discountPercent: 20,
    discountedPrice: 879,
    onSale: true,
    outOfStock: false,
    rating: 4.7,
    trending: false,
  },
  {
    _id: uuid(),
    productName: "Lowepro ProTactic BP 450 AW II Camera Backpack",
    productDescription: "Camera Backpack with Customizable Interior",
    productImage:
      "https://images.unsplash.com/photo-1537716316812-50d2f4d13a31",
    categoryName: "bags",
    price: 249,
    discountPercent: 10,
    discountedPrice: 224,
    onSale: true,
    outOfStock: false,
    rating: 4.6,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Sony a7 III",
    productDescription: "Full-Frame Mirrorless Camera",
    productImage:
      "https://images.unsplash.com/photo-1589651812743-e245fd1bfe44",
    categoryName: "cameras",
    price: 1999,
    discountPercent: 0,
    discountedPrice: 1999,
    onSale: false,
    outOfStock: true,
    rating: 4.9,
    trending: false,
  },
  {
    _id: uuid(),
    productName: "Godox SL-60W LED Video Light",
    productDescription:
      "A powerful LED light designed for video and photography, featuring adjustable color temperature, wireless remote control, and quiet fan cooling.",
    productImage:
      "https://images.unsplash.com/photo-1618856364133-1d98a09a9a7a",
    categoryName: "lighting",
    price: 139.0,
    discountPercent: 0,
    onSale: false,
    outOfStock: true,
    rating: 4.2,
    trending: false,
  },
  {
    _id: uuid(),
    productName: "Nikon D850 DSLR Camera",
    productDescription:
      "A powerful DSLR camera that features a high-resolution sensor and fast autofocus.",
    productImage:
      "https://images.unsplash.com/photo-1584470589654-07d55cf5a4b8?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    categoryName: "cameras",
    price: 2799.99,
    discountPercent: 15,
    discountedPrice: 2379.99,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Canon EF 50mm f/1.4 USM Standard Lens",
    productDescription:
      "A fast and sharp lens that is ideal for low-light photography and portraits.",
    productImage:
      "https://images.unsplash.com/photo-1586875940405-a57d07b4dcd9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    categoryName: "lenses",
    price: 399.99,
    discountPercent: 0,
    discountedPrice: 399.99,
    onSale: false,
    outOfStock: false,
    rating: 4.6,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Sigma 24-70mm f/2.8 DG OS HSM Art Lens",
    productDescription:
      "A versatile and high-quality zoom lens that delivers sharp and detailed images.",
    productImage:
      "https://images.unsplash.com/photo-1585500068746-0b7d763e2e92?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
    categoryName: "lenses",
    price: 1299.99,
    discountPercent: 20,
    discountedPrice: 1039.99,
    onSale: true,
    outOfStock: false,
    rating: 4.8,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "SanDisk Extreme Pro SDXC UHS-I Memory Card",
    productDescription:
      "The SanDisk Extreme Pro SDXC UHS-I Memory Card is a high-speed card that is perfect for recording 4K video and taking high-resolution photos. It features a read speed of up to 170MB/s and a write speed of up to 90MB/s.",
    productImage:
      "https://www.bhphotovideo.com/images/images1000x1000/sandisk/extreme_pro_sdxc_uhs_i_memory_card_1324683.jpg",
    categoryName: "accessories",
    price: 49.99,
    discountPercent: 10,
    discountedPrice: 44.99,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Neewer NW-700 Professional On-Camera Shotgun Microphone",
    productDescription:
      "The Neewer NW-700 Professional On-Camera Shotgun Microphone is a high-quality microphone that is perfect for recording audio for video. It features a cardioid pickup pattern, a low-cut filter, and a wind muff.",
    productImage:
      "https://www.bhphotovideo.com/images/images1000x1000/neewer/nw_700_professional_on_camera_shotgun_microphone_1324685.jpg",
    categoryName: "accessories",
    price: 79.99,
    discountPercent: 15,
    discountedPrice: 66.99,
    onSale: true,
    outOfStock: false,
    rating: 4.7,
    trending: true,
  },
  {
    _id: uuid(),
    productName: "Joby GorillaPod SLR-Zoom Tripod",
    productDescription:
      "The Joby GorillaPod SLR-Zoom Tripod is a flexible and versatile tripod that is perfect for holding your camera steady. It features three articulating legs that can be wrapped around objects, and a ball head that allows you to quickly and easily adjust the angle of your camera.",
    productImage:
      "https://www.bhphotovideo.com/images/images1000x1000/joby/gorillapod_slr_zoom_tripod_1324687.jpg",
    categoryName: "accessories",
    price: 59.99,
    discountPercent: 20,
    discountedPrice: 47.99,
    onSale: true,
    outOfStock: false,
    rating: 4.9,
    trending: false,
  },
  {
    _id: uuid(),
    productName: "LensPen Lens Cleaning Pen",
    productDescription:
      "The LensPen Lens Cleaning Pen is a small and portable tool that is perfect for cleaning your lenses. It features a soft brush that removes dust and dirt, and a solvent-free cleaning fluid that removes fingerprints and smudges.",
    productImage:
      "https://www.bhphotovideo.com/images/images1000x1000/lenspen/lens_cleaning_pen_1324689.jpg",
    categoryName: "accessories",
    price: 19.99,
    discountPercent: 10,
    discountedPrice: 17.99,
    onSale: true,
    outOfStock: false,
    rating: 4.5,
    trending: false,
  },
];
